# -*- coding: utf-8 -*-
"""Spotify

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOUmAx3IbHJswy1lfWorFWipRC2EYHvZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset fictício de escutas
data = {
    "usuario": ["u1","u1","u2","u2","u3","u3","u3","u4","u4"],
    "artista": [
        "Twice","Twice",
        "Katseye","Billie Eilish",
        "Stray Kids","Twice","Billie Eilish",
        "Katseye","Stray Kids"
        ],
    "musica": [
        "Cheer Up","Heartbreak Avenue",
        "Gnarly","Lunch",
        "Maniac","Fancy","Happier Than Ever",
        "M.I.A.","God's Menu"
        ],
    "tempo_segundos": [209,196,137,179,182,213,298,129,167],
    "pulos": [1,0,0,0,0,0,1,0,0]
}

df = pd.DataFrame(data)

# Estatísticas descritivas básicas
print(df[['tempo_segundos','pulos']].describe())

# Artistas mais ouvidos
print("\nTop artistas por número de execuções:")
print(df['artista'].value_counts())

# Taxa de pulo por artista
skip_rate = df.groupby('artista')['pulos'].mean()
print("\nTaxa média de pulo por artista:")
print(skip_rate)

# Gráfico: tempo médio de escuta por artista
avg_time = df.groupby('artista')['tempo_segundos'].mean().reset_index()
sns.barplot(x='artista', y='tempo_segundos', data=avg_time)
plt.title("Tempo médio de escuta por artista")
plt.xticks(rotation=15)
plt.show()