# -*- coding: utf-8 -*-
"""Exemplo de código

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-dUArFe8lXQ9ozAGr-n_jaXLDoE9XO60
"""

# 1. Importar bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 2. Criar dataset fictício de vendas
data = {
    "Loja": ["A", "B", "C", "A", "B", "C", "A", "B", "C", "A", "B", "C"],
    "Vendas": [200, 340, 150, 400, 300, 250, 500, 320, 180, 450, 370, 220],
    "Clientes": [30, 50, 20, 60, 45, 35, 80, 55, 25, 75, 60, 28]
}
df = pd.DataFrame(data)

# 3. Estatísticas descritivas
print(df.describe())

# Média e Mediana
print("\nMédia de vendas:", df["Vendas"].mean())
print("Mediana de vendas:", df["Vendas"].median())

# Quartis
print("Quartis de vendas:\n", df["Vendas"].quantile([0.25, 0.5, 0.75]))

# 4. Visualizações
plt.figure(figsize=(10,5))

# Histograma
plt.subplot(1,2,1)
sns.histplot(df["Vendas"], bins=5, kde=True)
plt.title("Distribuição das Vendas")

# Boxplot
plt.subplot(1,2,2)
sns.boxplot(x="Loja", y="Vendas", data=df)
plt.title("Boxplot de Vendas por Loja")

plt.tight_layout()
plt.show()